export enum tagTypes {
  client_type = "client-type",
  department = "department",
  designation = "designation",
  user = "user",
  profile = "profile",
  country = "country",
  division = "division",
  district = "district",
  admin = "admin",
  employee = "employee",
  client = "client",
}

// Defining the content, category, and authority as constant objects
export const contentTags = {
  menu: "menu",
  submenu: "submenu",
  webpage: "webpage",
  page_section: "pageSection",
  blog: "blog",
  hero_section: "heroSection",
  team_member: "teamMember",
  core_values: "coreValues",
  faq: "faq",
  memories: "memories",
  company_video: "companyVideo",
  category: {
    blog: "blogCategory",
    ft: "ftCategory",
    rp: "rpCategory",
  },
  authority: {
    ft: "ftAuthority",
  },
  resource_portal: "resourcePortal",
  forms_template: "formsAndTemplates",
};

export const tagTypesList = [
  tagTypes.client_type,
  tagTypes.user,
  tagTypes.department,
  tagTypes.designation,
  tagTypes.country,
  tagTypes.division,
  tagTypes.district,
  tagTypes.profile,
  tagTypes.admin,
  tagTypes.employee,
  tagTypes.client,
  contentTags.menu,
  contentTags.submenu,
  contentTags.webpage,
  contentTags.page_section,
  contentTags.blog,
  contentTags.hero_section,
  contentTags.team_member,
  contentTags.core_values,
  contentTags.faq,
  contentTags.memories,
  contentTags.company_video,
  contentTags.category.blog,
  contentTags.category.ft,
  contentTags.category.rp,
  contentTags.authority.ft,
  contentTags.resource_portal,
  contentTags.forms_template,
];
