import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Toaster } from "sonner";
import Providers from "@/lib/Providers/Providers";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Common Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={""}>
          <AppRouterCacheProvider>
            <Toaster richColors position="bottom-right" />

            {children}
          </AppRouterCacheProvider>
        </body>
      </html>
    </Providers>
  );
}
